#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
wishful_simple_local_controller.py: First implementation of WiSHFUL controller

Usage:
   wishful_simple_local_controller.py [options] [-q | -v]

Options:
   --logfile name      Name of the logfile
   --config configFile Config file path

Example:
   ./wishful_simple_local_controller -v --config ./config.yaml 

Other options:
   -h, --help          show this help message and exit
   -q, --quiet         print less text
   -v, --verbose       print more text
   --version           show version and exit
"""

import sys
import datetime
import logging
import wishful_agent
import time
import yaml
from scapy.all import *
import wishful_upis as upis
from wishful_framework import TimeEvent, PktEvent, MovAvgFilter, PeakDetector, Match, Action, Permanance, PktMatch, FieldSelector

__author__ = "Piotr Gawlowicz"
__copyright__ = "Copyright (c) 2015, Technische Universität Berlin"
__version__ = "0.1.0"
__email__ = "gawlowicz@tkn.tu-berlin.de"


simpleModuleLogger = logging.getLogger('SimpleModule2')
simpleModuleLogger.setLevel(logging.CRITICAL)

log = logging.getLogger('wishful_agent.main')
agent = wishful_agent.Agent(local=True)
controller = agent.get_local_controller()


@controller.set_default_callback()
def default_callback(cmd, data):
    print "{} DEFAULT CALLBACK : Cmd: {}, Returns: {}".format(datetime.datetime.now(), cmd, data)


def main(args):
    log.debug(args)

    config_file_path = args['--config']
    config = None
    with open(config_file_path, 'r') as f:
        config = yaml.load(f)

    agent.load_config(config)
    agent.run()
   
    #control loop
    while True:
        #######################################################################################
        print "{} Get new generator".format(datetime.datetime.now())
        myGenerator = controller.generator.start(
                                      event=TimeEvent(func=upis.radio.get_noise, kwargs={}, interval=0.2, iface="wlan0"),
                                      filters=[MovAvgFilter(10)])

        print "{} New generator with ID: {}".format(datetime.datetime.now(), myGenerator.id)

        sampleNum = 20
        i = 0
        for sample in myGenerator:
            print i, sample
            i = i + 1
            if i == sampleNum:
              break

        retVal = myGenerator.stop()
        print "{} Generator with ID: {} was {}".format(datetime.datetime.now(), myGenerator.id, retVal)
        time.sleep(2)
        #######################################################################################


        print "{} Get new generator".format(datetime.datetime.now())
        myGenerator = controller.generator.start(
                                    event=TimeEvent(func=upis.radio.get_rssi, kwargs={}, iface="wlan0"),
                                    filters=[MovAvgFilter(10)])

        print "{} New generator with ID: {}".format(datetime.datetime.now(), myGenerator.id)

        sampleNum = 20
        i = 0
        for sample in myGenerator:
            print i, sample
            i = i + 1
            if i == sampleNum:
              break

        retVal = myGenerator.stop()
        print "{} Generator with ID: {} was {}".format(datetime.datetime.now(), myGenerator.id, retVal)
        time.sleep(2)


if __name__ == "__main__":
    try:
        from docopt import docopt
    except:
        print("""
        Please install docopt using:
            pip install docopt==0.6.1
        For more refer to:
        https://github.com/docopt/docopt
        """)
        raise

    args = docopt(__doc__, version=__version__)

    log_level = logging.INFO  # default
    if args['--verbose']:
        log_level = logging.DEBUG
    elif args['--quiet']:
        log_level = logging.ERROR

    logfile = None
    if args['--logfile']:
        logfile = args['--logfile']

    logging.basicConfig(filename=logfile, level=log_level,
        format='%(asctime)s - %(name)s.%(funcName)s() - %(levelname)s - %(message)s')

    try:
        main(args)
    except KeyboardInterrupt:
        log.debug("Controller exits")
    finally:
        log.debug("Exit")
        agent.stop()