#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
RAS implementation in WiSHFUL Project

Usage:
   showcase3_controller_power.py [options] [-q | -v]

Options:
   --logfile name      Name of the logfile
   --config configFile Config file path

Example:
   ./showcase3_controller_power -v --config ./controller_config.yaml

Other options:
   -h, --help          show this help message and exit
   -q, --quiet         print less text
   -v, --verbose       print more text
   --version           show version and exit
"""

"""
DEMO visualizer START

    ssh -L 8300:"pc controlle node":8300 dgarlisi@ops.wilab2.ilabt.iminds.be -v

    eg. ssh -L 8300:apuN4:8300 dgarlisi@ops.wilab2.ilabt.iminds.be -v


    on local pc
        python demo_visualizer.py
"""


"""
DEMO START

 on not RAS station nodes
    sudo ./wishful_ras_agent --config agent_cfg.yaml

 on RAS station node
    sudo ./wishful_ras_agent --config  agent_ras_cfg.yaml

 on PC node
    ./wishful_ras_controller --config controller_cfg.yaml
"""


from scapy.all import *
import threading
import datetime
import logging
import sys
import time
import gevent
import signal
import os
import yaml
import zmq
import json


sys.path.append('../../')
sys.path.append("../../agent_modules/wifi_ath")
sys.path.append("../../agent_modules/wifi_wmp")
sys.path.append("../../agent_modules/wifi")
sys.path.append('../../upis')
sys.path.append('../../framework')
sys.path.append('../../agent')
sys.path.append('../../controller')

import wishful_controller
import wishful_upis as upis
from react_local_control_program import react

__author__ = "Fabrizio Giuliano"
__copyright__ = "Copyright (c) 2015, CNIT"
__version__ = "0.1.0"
__email__ = "fabrizio.giuliano@cnit.it"


"""
NODE IP

apuN4 : 10.11.16.104
apuT1 : 10.11.16.126
apuU1 : 10.11.16.130
apuO2 : 10.11.16.107
apuP4 : 10.11.16.112
apuU4 : 10.11.16.132
apu04 : 10.11.16.108 (RAS)
apuO5 : 10.11.16.109
"""


"""
Setting of experiment nodes, ip address and name
"""
#PC
controller_PC_name = "apuN4"
controller_PC_ip_address = "10.11.16.104"
controller_PC_interface = "eth0"

# AP1 set in monitor on channel 40
ap1_name = "apuT1"
ap1_ip = "10.11.16.126"
ap1_wlan_interface = "wlan0"

# STA1 set in monitor on channel 40
sta1_name = "apu04"
sta1_ip = "10.11.16.108"
sta1_wlan_interface = "wlan0"

# AP2
ap2_name = "apuU1"
ap2_ip = "10.11.16.130"
ap2_wlan_interface = "wlan0"

# STA2
sta2_name = "apuU4"
sta2_ip = "10.11.16.132"
sta2_wlan_interface = "wlan0"


#Nodes number
nodes_number=4
ap_wlan_interface = "wlan0"
sta_wlan_interface = "wlan0"

# BSSID of our Network
network_bssid = "wishful_ras_example"
group_name = "ras_example"

"""
END setting of experiment nodes
"""

log = logging.getLogger('wishful_agent.main')
controller = wishful_controller.Controller()

nodes = []
configuration_message_for_visualizzer = {}
ap1_node = None
sta1_node= None

ap2_node = None
sta2_node= None


@controller.new_node_callback()
def new_node(node):
    nodes.append(node)
    print("New node appeared:")
    print(node)


@controller.node_exit_callback()
def node_exit(node, reason):
    if node in nodes:
        nodes.remove(node);
    print("NodeExit : NodeID : {} Reason : {}".format(node.id, reason))


@controller.set_default_callback()
def default_callback(group, node, cmd, data):
    print("{} DEFAULT CALLBACK : Group: {}, NodeName: {}, Cmd: {}, Returns: {}".format(datetime.datetime.now(), group, node.name, cmd, data))


def setAP(controller, node, essid, conf_file, channel):
    """ This function use WiSHFUL UPI functions to perform an IEEE 802.11 infrastructure BSS, the "node" parameter is used as
        Network Access Point. The WiSHFUL UPI used hostapd daemon to create the network.

    :param controller: framework controller object
    :param node: elected Access Point Node
    :param essid: the network SSID
    """

    #This UPI function stops the hostpad daemon, if present on node
    rvalue = controller.nodes(node).net.stop_hostapd()
    #This UPI function sets the node ip address on a specific interface
    rvalue = controller.nodes(node).net.set_ip_address(ap_wlan_interface, '192.168.3.' + str(node.ip[9:12]))
    #This UPI function sets the node modulation rate (value in Mbps)
    #rvalue = controller.nodes(node).radio.set_modulation_rate(54)
    gevent.sleep(1)
    #This UPI function sets the hostapd configuration (starting from a generic file set interface, channel and SSID )
    rvalue = controller.nodes(node).net.set_hostapd_conf(ap_wlan_interface, conf_file, channel, essid)
    #This UPI function starts the hostapd daemon (it uses a specific hostapd.conf file present in the experiment directory
    rvalue = controller.nodes(node).net.start_hostapd(conf_file)
    #This UPI function sets the node power (value in dBm)
    #rvalue = controller.nodes(node).radio.set_power(15)


def setSTA(controller, node, essid):
    """ This function use WiSHFUL UPI functions to connect a node to a IEEE 802.11 infrastructure BSS, the function
    performs 10 attempts before to return a failure state.

    :param controller: framework controller object
    :param node: elected station node by associate
    :param essid: the network SSID

    :return connected: True if the connection has been successful, False in other cases.
    """

    #This UPI function stops the hostpad daemon, if present on node
    rvalue = controller.nodes(node).net.stop_hostapd()
    #This UPI function sets the node ip address on a specific interface
    rvalue = controller.nodes(node).net.set_ip_address(sta_wlan_interface, '192.168.3.' + str(node.ip[9:12]))
    #This UPI function sets the node power (value in dBm)
    #rvalue = controller.nodes(node).radio.set_power(15)
    #This UPI function sets the node modulation rate (value in Mbps)
    #rvalue = controller.nodes(node).radio.set_modulation_rate(54)
    connected = False
    for ii in range(10):
        #This UPI function sets the node modulation rate (value in Mbps)
        rvalue = controller.nodes(node).net.connect_to_network(sta_wlan_interface, essid)
        gevent.sleep(2)
        #This UPI function gets the node connection state
        rvalue = controller.nodes(node).net.network_dump(sta_wlan_interface)
        flow_info_lines = rvalue.rstrip().split('\n')
        if flow_info_lines[0][0:9] == "Connected" :
                connected = True
                break
    #This UPI function sets the node power (value in dBm)
    #rvalue = controller.nodes(node).radio.set_power(15)
    return connected

rxPkts1 = {}
def csResultCollector1(group, node, data):
    messagedata = data
    log.info('1 - receives data msg at %s - %s' % (str(node.ip), str(messagedata) ))

    if messagedata is None:
        rxPkts1['num'] = 0
        rxPkts1['avg_power'] = 0
    else:
        rxPkts1['num'] = messagedata['num']
        rxPkts1['avg_power'] = messagedata['avg_power']



rxPkts2 = {}
def csResultCollector2(group, node, data):
    messagedata = data
    log.info('2 - receives data msg at %s - %s' % (str(node.ip), str(messagedata) ))

    if messagedata is None:
        rxPkts2['num'] = 0
        rxPkts2['avg_power'] = 0
    else:
        rxPkts2['num'] = messagedata['num']
        rxPkts2['avg_power'] = messagedata['avg_power']

    send_socket_visualizer(messagedata, node.ip)


def csResultCollector3(group, node, data):
    global configuration_message_for_visualizzer
    global sta1_node
    messagedata = data
    log.info('3 - at %s traffic THR %s ' % (str(node.ip), str(messagedata) ))
    send_socket_visualizer(messagedata, node.ip)
    send_socket_visualizer(configuration_message_for_visualizzer, sta1_node.ip)



def csResultCollector4(group, node, data):
    messagedata = data
    log.info('4 - at %s traffic THR %s ' % (str(node.ip), str(messagedata) ))
    send_socket_visualizer(messagedata, node.ip)


socket_visualizer = None

def setup_socket_visualizer():
    #setup socket to send information outside the laboratory
    ''' implement message zmq for realtime visualizer '''
    global socket_visualizer
    port = "8300"
    context = zmq.Context()
    socket_visualizer = context.socket(zmq.PUB)
    socket_visualizer.bind("tcp://*:%s" % port)
    print('start server on 8300 port ... sending protocol information to remote DEMO console')


def send_socket_visualizer(message, node_ip_address):
    global socket_visualizer
    #send information to visualizer outside the laboratory
    message['node_ip_address']=node_ip_address
    socket_visualizer.send_json(message)

def send_react(node_id):
     for i in range(0,10): 
       my_mac= controller.nodes(node_id).net.get_iface_hw_addr(iface="wlan0")
       my_data={'name':'fabrizio'}
       json_data=json.dumps(my_data)
       a=RadioTap()/Dot11(addr1="ff:ff:ff:ff:ff:ff", addr2=my_mac, addr3="ff:ff:ff:ff:ff:ff")/json_data
       rvalue = controller.nodes(node_id).net.inject_frame(iface="mon0", frame=a, is_layer_2_packet=True, tx_count=1, pkt_interval=1)
       gevent.sleep(1)

def main(args):

    global configuration_message_for_visualizzer
    global ap1_node
    global sta1_node

    global ap2_node
    global sta2_node

    log.debug(args)

    config_file_path = args['--config']
    config = None
    with open(config_file_path, 'r') as f:
        config = yaml.load(f)

    controller.load_config(config)

    #Start controller
    controller.start()

    #Setup socket visualizer to send information to demo visualizer
    setup_socket_visualizer()

    #control loop
    freq=2462
    while True:
        gevent.sleep(5)
        print("\nConnected nodes", [str(node.name) for node in nodes])
	
        if len(nodes) == 2:
          for ii in range(0, len(nodes)):
           print("ip={}".format(nodes[ii].ip))
           if nodes[ii].ip == "10.8.9.3":
             print("Found ath9k")
             rvalue = controller.nodes(nodes[ii]).net.start_adhoc("ath9k","wlan0","wishful-react",freq,"10","6","192.168.0.111",250,"aa:bb:cc:dd:ee:ff",False)
             gevent.sleep(5)
             rvalue = controller.nodes(nodes[ii]).net.start_monitor("ath9k","wlan0")
             gevent.sleep(5)

           if nodes[ii].ip == "10.8.8.103":
             print("Found Alix")
             rvalue = controller.nodes(nodes[ii]).net.start_adhoc("b43","wlan0","wishful-react",freq,"10","6","192.168.0.112",250,"aa:bb:cc:dd:ee:ff",False)
             gevent.sleep(5)
             rvalue = controller.nodes(nodes[ii]).net.start_monitor("b43","wlan0")
             gevent.sleep(5)

          break

if __name__ == "__main__":
    try:
        from docopt import docopt
    except:
        print("""
        Please install docopt using:
            pip install docopt==0.6.1
        For more refer to:
        https://github.com/docopt/docopt
        """)
        raise

    args = docopt(__doc__, version=__version__)

    log_level = logging.DEBUG  # default
    if args['--verbose']:
        log_level = logging.DEBUG
    elif args['--quiet']:
        log_level = logging.ERROR

    logfile = None
    if args['--logfile']:
        logfile = args['--logfile']

    logging.basicConfig(filename=logfile, level=log_level,
        format='%(asctime)s - %(name)s.%(funcName)s() - %(levelname)s - %(message)s')

    try:
        main(args)
    except KeyboardInterrupt:
        log.debug("Controller exits")
    finally:
        log.debug("Exit")
        controller.stop()
