#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import datetime
import logging
import wishful_controller
import gevent
import wishful_upis as upis

import numpy
from matplotlib import pyplot

__author__ = "Piotr Gawlowicz, Matevz Vucnik"
__copyright__ = "Copyright (c) 2015, Technische Universität Berlin"
__version__ = "0.1.0"
__email__ = "gawlowicz@tkn.tu-berlin.de, matevz.vucnik@ijs.si"

log = logging.getLogger('wishful_controller')
log_level = logging.INFO
logging.basicConfig(level=log_level, format='%(asctime)s - %(name)s.%(funcName)s() - %(levelname)s - %(message)s')

#Create controller
controller = wishful_controller.Controller(dl="tcp://127.0.0.1:8990", ul="tcp://127.0.0.1:8989")

#Configure controller
controller.set_controller_info(name="WishfulController", info="WishfulControllerInfo")
controller.add_module(moduleName="discovery", pyModuleName="wishful_module_discovery_pyre",
                      className="PyreDiscoveryControllerModule", 
                      kwargs={"iface":"lo", "groupName":"wishful_1234", "downlink":"tcp://127.0.0.1:8990", "uplink":"tcp://127.0.0.1:8989"})

nodes = []

@controller.new_node_callback()
def new_node(node):
    nodes.append(node)
    print("New node appeared:")
    print(node)


@controller.node_exit_callback()
def node_exit(node, reason):
    if node in nodes:
        nodes.remove(node);
    print("NodeExit : NodeID : {} Reason : {}".format(node.id, reason))


@controller.set_default_callback()
def default_callback(group, node, cmd, data):
    print("{} DEFAULT CALLBACK : Group: {}, NodeName: {}, Cmd: {}, Returns: {}".format(datetime.datetime.now(), group, node.name, cmd, data))


@controller.add_callback(upis.radio.get_channel)
def get_channel_reponse(group, node, data):
    print("{} get_channel_reponse : Group:{}, NodeId:{}, msg:{}".format(datetime.datetime.now(), group, node.id, data))


def print_response_sensor(group, node, data):
    print("{} Print response : Group:{}, NodeIP:{}".format(datetime.datetime.now(), group, node.ip))

    f_mhz = numpy.array(data['frequency']) / 1e6

    pyplot.clf()
    pyplot.grid()
    pyplot.xlabel("frequency [MHz]")
    pyplot.ylabel("power [dBm]")

    # Plot data
    pyplot.plot(f_mhz, data['power'])

    pyplot.axis([min(f_mhz), max(f_mhz), -110, -50])
    pyplot.show(block=False)
    pyplot.pause(0.001)

def print_response_generator(group, node, data):
    print("{} Print response : Group:{}, NodeIP:{}, Result:{}".format(datetime.datetime.now(), group, node.ip, data)) 

try:
    #Start controller
    controller.start()

    #control loop
    while True:
        print("\n")
        print("Connected nodes", [str(node.name) for node in nodes])
        if nodes:
            controller.callback(print_response_sensor).node(nodes[0]).radio.iface("ismtv").get_measurements([868.3e6, 919.0e6, 400e3])
            controller.callback(print_response_generator).node(nodes[0]).radio.iface("ismtv").play_waveform(iface=10, freq=868e6, power_lvl=-10)

        gevent.sleep(30)

except KeyboardInterrupt:
    print("Controller exits")
finally:
    controller.stop()
