#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import datetime
import logging
import wishful_controller
import gevent
import wishful_upis as upis
import os
import time
import wishful_module_gnuradio

__author__ = "Maicon Kist"
__copyright__ = "Copyright (c) 2017 Connect Centre - Trinity College Dublin" 
__version__ = "0.1.0"
__email__ = "kistm@tcd.ie"


log = logging.getLogger('wishful_controller')
log_level = logging.INFO
logging.basicConfig(level=log_level, format='%(asctime)s - %(name)s.%(funcName)s() - %(levelname)s - %(message)s')

#Create controller
# ::TRICKY:: update IP addresses to external interface
controller = wishful_controller.Controller(dl="tcp://192.168.5.55:8990", ul="tcp://192.168.5.55:8989")

#Configure controller
controller.set_controller_info(name="WishfulController", info="WishfulControllerInfo")
# ::TRICKY:: update IP addresses to external interface
controller.add_module(moduleName="discovery", pyModuleName="wishful_module_discovery_pyre",
                      className="PyreDiscoveryControllerModule",
                      kwargs={"iface":"ens3", "groupName":"wishful_1234", "downlink":"tcp://192.168.5.55:8990", "uplink":"tcp://192.168.5.55:8989"})

nodes = []
the_node = None

@controller.new_node_callback()
def new_node(node):
    nodes.append(node)
    print("New node appeared:")
    print(node)

@controller.node_exit_callback()
def node_exit(node, reason):
    if node in nodes:
        nodes.remove(node);
    print("NodeExit : NodeID : {} Reason : {}".format(node.id, reason))

@controller.set_default_callback()
def default_callback(group, node, cmd, data):
    print("{} DEFAULT CALLBACK : Group: {}, NodeName: {}, Cmd: {}, Returns: {}".format(datetime.datetime.now(), group, node.name, cmd, data))


@controller.add_callback(upis.radio.get_parameters)
def get_vars_response(group, node, data):
    print("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX HAAAA PEAO")
    print("{} get_channel_reponse : Group:{}, NodeId:{}, msg:{}".format(datetime.datetime.now(), group, node.id, data))


if __name__ == "__main__":

    TOTAL_NODES = 2
    NODE_NAMES = ["tx", "rx1", "rx2"]

    # list of files that will be send to agents
    files = {
        "tx" : 	"/home/nodeuser/gr-hydra/apps/video_benchmark_tx.py",
	    "rx" :  "/home/nodeuser/gr-hydra/apps/video_rx.py"
    }

    # What code each node will execute. Node 0 is TX, Node 1 is RX
    nodes_to_program = {
	    "tx" : "tx",
        "rx1": "rx", 
        "rx2": "rx", 
    }

    # open files, read content, keep it in codes dict
    program = {}
    for _k, _v in files.items():
        with open(_v, "r") as fid:
            program[_k] = fid.read()

    #Start controller
    controller.start()

    running = False
    first_time = True

    while len(nodes) < TOTAL_NODES:
    # Waiting for 2 nodes
        print("%d nodes connected. Waiting for %d more" % (len(nodes), TOTAL_NODES - len(nodes)))
        gevent.sleep(2)

    print("All nodes connected. Starting showcase...")

    for idx, node in enumerate(nodes):
        if node.name not in NODE_NAMES:
            self.log.info("Node '%s' is not part of this showcase. Ignoring it" % (node.name, ))

        else:
            program_name = nodes_to_program[node.name]
            program_code = program[program_name] 

            controller.blocking(False).node(node).radio.iface('usrp').activate_radio_program({'program_name': program_name, 'program_code': program_code, 'program_type': 'py'})

    #control loop
    while True:
        if nodes:
            gvals = ['svl_center_freq','svl_bandwidth',]

            # TRICKY: gets are assynchronous. callback for get_parameters is called automatically
            print("Requesting vals")
            controller.blocking(False).node(nodes[0]).radio.iface('usrp').get_parameters(gvals)

            """
            if running:
                print("Deactivating program %s" % (program_name, ))
                #controller.blocking(False).node(nodes[0]).radio.iface('usrp').deactivate_radio_program({'program_name': program_name})
                running = False
            else:
                print("Activating program %s" % (program_name, ))
                #controller.blocking(False).node(nodes[0]).radio.iface('usrp').activate_radio_program({'program_name': program_name})
                running = True
            """

        else:
            print("no nodes")

        gevent.sleep(2)

    controller.stop()
