ELF_PROGRAM_FILE_NAME=$1
LINKER_SCRIPT=$2
ELF_OBJECT_FILES="${@:3}"

echo "Will merge $ELF_OBJECT_FILES into $ELF_PROGRAM_FILE_NAME using $LINKER_SCRIPT" 

arm-none-eabi-ld -r -o $ELF_PROGRAM_FILE_NAME.merged $ELF_OBJECT_FILES -T $LINKER_SCRIPT