#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
global_controller.py: Example of a hierarchical controller. Here
a global controller deploys local control program on a remote node
and communicates with it by means of exchange of control messages.

Usage:
   global_controller.py [options] [-q | -v]

Options:
   --logfile name      Name of the logfile
   --config configFile Config file path

Example:
   ./global_controller -v --config ./config.yaml

Other options:
   -h, --help          show this help message and exit
   -q, --quiet         print less text
   -v, --verbose       print more text
   --version           show version and exit
"""

import sys
import datetime
import logging
import random
import wishful_controller
import gevent
import yaml
import wishful_upis as upis

from local_control_program import my_local_control_program

__author__ = "Piotr Gawlowicz, Anatolij Zubow"
__copyright__ = "Copyright (c) 2016, Technische Universität Berlin"
__version__ = "0.1.0"


log = logging.getLogger('wishful_controller.main')
controller = wishful_controller.Controller()
nodes = []

@controller.new_node_callback()
def new_node(node):
    nodes.append(node)
    print("New node appeared:")
    print(node)


@controller.node_exit_callback()
def node_exit(node, reason):
    if node in nodes:
        nodes.remove(node);
    print("NodeExit : NodeID : {} Reason : {}".format(node.id, reason))


@controller.set_default_callback()
def default_callback(group, node, cmd, data):
    print("DEFAULT CALLBACK : Group: {}, NodeName: {}, Cmd: {}, Returns: {}".format(group, node.name, cmd, data))


def main(args):
    log.debug(args)

    config_file_path = args['--config']
    config = None
    with open(config_file_path, 'r') as f:
        config = yaml.load(f)

    controller.load_config(config)
    controller.start()
   
    # control loop
    while True:
        print("Connected nodes", [str(node.name) for node in nodes])

        if nodes:
            print("Deploy local control program on a remote node")
            lcpDescriptor = controller.node(nodes[0]).hc.start_local_control_program(program=my_local_control_program)

            msgNum = 5
            while msgNum:
                newCh = random.randint(1, 30)
                print("Send ctrl message to remote control program")
                lcpDescriptor.send({"new_channel": newCh})

                while True:
                    msg = lcpDescriptor.recv(timeout=1)
                    if msg:
                        print("Recv ctrl message from remote local control program")
                        msgNum = msgNum - 1
                        break

                gevent.sleep(5)

            print("Terminate remote local control program")
            lcpDescriptor.close()

        gevent.sleep(10)


if __name__ == "__main__":
    try:
        from docopt import docopt
    except:
        print("""
        Please install docopt using:
            pip install docopt==0.6.1
        For more refer to:
        https://github.com/docopt/docopt
        """)
        raise

    args = docopt(__doc__, version=__version__)

    log_level = logging.INFO  # default
    if args['--verbose']:
        log_level = logging.DEBUG
    elif args['--quiet']:
        log_level = logging.ERROR

    logfile = None
    if args['--logfile']:
        logfile = args['--logfile']

    logging.basicConfig(filename=logfile, level=log_level,
        format='%(asctime)s - %(name)s.%(funcName)s() - %(levelname)s - %(message)s')

    try:
        main(args)
    except KeyboardInterrupt:
        log.debug("Controller exits")
    finally:
        log.debug("Exit")
        controller.stop()